## YAML Config.
---

# server
server:
  applicationConnectors:
    - type: https
      port: 6969
      keyStorePath: keystore.jks
      keyStorePassword: iprwcapi
      validateCerts: false
      validatePeers: false

database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:/home/pi/iprwc/database.db
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect

enableDebugResource: false
